Updating wlcg-wpad for Python3 and EL9
DrDaveD/wlcg-wpad pull request #5
Opened 2024-05-08 22:13 UTC by cvuosalo

The `wlcg-wpad` scripts were updated to support EL9 and converted to Python3. Also, the build script `build-wlcg-wpad` is being added.

These changes were tested by installing the RPM on an EL9 machine and sending it the query `curl -H Host:wlcg-wpad.fnal.gov http://vuosalox.hep.wisc.edu/wpad.dat`, which produced the correct output for choosing a proxy.

2024-05-08 22:32 UTC, DrDaveD requested changes

2024-05-08 22:32 UTC, DrDaveD commented on rpm/wlcg-wpad.spec
>  Requires: mod_wsgi
In order to make this work also on el8 (although we shouldn't really need it), make this be
```
%if %{rhel} < 9
Requires: python3-mod_wsgi
%else
Requires: mod_wsgi
%endif
```

2024-05-09 19:34 UTC, cvuosalo commented on rpm/wlcg-wpad.spec
>  Requires: mod_wsgi
I added EL8 support. Note that the RPM must be built on EL8 in order for it to be installed on EL8, and similarly for EL9.

2024-05-09 20:55 UTC, DrDaveD approved these changes

2024-05-09 20:55 UTC, merged